/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#cdc0e9",
        "on-surface": "#e6e0e9",
        "inverse-surface": "#e6e0e9",
        "inverse-primary": "#6750a4",
        "on-background": "#e6e0e9",
        "surface-variant": "#36343a",
        "surface-bright": "#3b383e",
        "on-error-container": "#ffdad6",
        "surface-tint": "#cfbcff",
        "primary-container": "#6750a4",
        "tertiary-fixed-dim": "#e7c365",
        "on-tertiary-fixed": "#241a00",
        "on-primary": "#381e72",
        "surface-container-high": "#2b292f",
        "on-surface-variant": "#cbc4d2",
        "inverse-on-surface": "#322f35",
        "surface": "#141218",
        "surface-container-lowest": "#0f0d13",
        "surface-container": "#211f24",
        "secondary-fixed-dim": "#cdc0e9",
        "surface-dim": "#141218",
        "surface-container-low": "#1d1b20",
        "on-secondary": "#342b4b",
        "outline": "#948e9c",
        "on-secondary-fixed": "#1f1635",
        "on-error": "#690005",
        "on-tertiary": "#3e2e00",
        "on-primary-fixed-variant": "#4f378a",
        "on-secondary-container": "#bfb2da",
        "tertiary-fixed": "#ffdf93",
        "tertiary": "#e7c365",
        "primary-fixed-dim": "#cfbcff",
        "on-tertiary-container": "#503d00",
        "error-container": "#93000a",
        "secondary-container": "#4d4465",
        "on-tertiary-fixed-variant": "#594400",
        "tertiary-container": "#c9a74d",
        "primary": "#cfbcff",
        "primary-fixed": "#e9ddff",
        "secondary-fixed": "#e9ddff",
        "on-primary-fixed": "#22005d",
        "on-primary-container": "#e0d2ff",
        "surface-container-highest": "#36343a",
        "error": "#ffb4ab",
        "background": "#141218",
        "outline-variant": "#494551",
        "on-secondary-fixed-variant": "#4b4263",
        "deep-slate": "#1F2A38",
        "electric-blue": "#00A8E8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "40px",
        "margin": "32px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "gutter": "20px",
        "xs": "4px",
        "unit": "4px"
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "label-sm": ["Inter"],
        "headline-md": ["Manrope"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Manrope"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
